//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKeyApp.Wpf {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class AutoKeySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AutoKeySettings defaultInstance = ((AutoKeySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AutoKeySettings())));
        
        public static AutoKeySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F4")]
        public string ChosenKey {
            get {
                return ((string)(this["ChosenKey"]));
            }
            set {
                this["ChosenKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int TimeSpan {
            get {
                return ((int)(this["TimeSpan"]));
            }
            set {
                this["TimeSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Min")]
        public string ChosenTimeSpan {
            get {
                return ((string)(this["ChosenTimeSpan"]));
            }
            set {
                this["ChosenTimeSpan"] = value;
            }
        }
    }
}
